apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: webhook-interceptor
  namespace: cicd
spec:
  serviceAccountName: tekton-triggers-webhook-sa
  triggers:
    - name: webhook-listener
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "secretRef"
              value:
                secretName: webhook-secret
                secretKey: secret
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "only when PRs are opened"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: webhook-pr-binding
      template:
        ref: webhook-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: webhook-pr-binding
  namespace: cicd
spec:
  params:
    - name: gitrevision
      value: $(body.pull_request.head.sha)
    - name: namespace
      value: cicd
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: webhook-template
  namespace: cicd
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: services-pipeline-run-
        namespace: cicd
      spec:
        taskRunSpecs:
        - pipelineTaskName: kn-deploy
          taskServiceAccountName: kn-deployer-account
        pipelineRef:
          name: services-pipeline
        podTemplate:
          securityContext:
            fsGroup: 65532
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: docker-credentials
          secret:
            secretName: docker-credentials
        params:
        - name: repo-url
          value: https://github.com/kryfitek/pulumi-knative.git
        - name: docker-repo
          value: docker.io/kryfitek
        - name: pathToContext
          value: src