apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-ingress-run
  namespace: cicd
spec:
  taskRef:
    name: create-ingress
  params:
  - name: CreateCertificate
    value: "true"
  - name: CertificateKeyPassphrase
    value: asecretphrase
  - name: CertificateSecretName
    value: ingresssecret
  - name: ExternalDomain
    value: webhook.34.73.155.235.nip.io
    # value: webhook.kryfitek.com
  - name: Service
    value: webhook-interceptor
  - name: ServicePort
    value: "8080"
  - name: Namespace
    value: cicd
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook